---

- name: Create prod directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    recurse: true
  with_items:
    - "{{ tpl_directories }}"

- name: Create fpm config directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0775
    recurse: true
  with_items:
    - "{{ tpl_fpm_config_directories }}"

- name: Generate Dockerfiles
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode: 0644
  with_items:
    - "{{ tpl_dockerfiles }}"

- name: Generate PHP configuration files for FPM builds
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode: 0644
  with_items:
    - "{{ tpl_fpm_configs }}"
  when: php_type == "fpm"

- name: Generate PHP configuration files for Supervisord builds
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode: 0644
  with_items:
    - "{{ tpl_supervisord_configs }}"
  when: php_type == "supervisord"

- name: Generate Dockerfile Goss tests
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    force: true
    mode:  0644
  with_items:
    - "{{ tpl_docker_tests }}"

...
